### ISSUE TITLE
Feedback for your W4 cultural blog post

### ISSUE THREAD

**Issue by gaillechua** [justkarenlo/justkarenlo.github.io#1]
Hi Karen! Just wanted to stop by and say that I read your post and found it very clear to read and relatable because, I too am a woman. I like how you brought up a real-life example in the article/video link you reference. Also good to hear about the positive efforts, it's always good to mention the silver lining -- I did the same :) If it's one small feedback to provide to your blog, it's that the link to the article was not too obvious. Perhaps consider changing un-clicked link text colors to a different color than white? Otherwise, your site design is beautiful! Intricate and very, very sophisticated. Kudos!

**Comment by justkarenlo** [comment]
Hey Gaille!

```
 Thanks so much for the visit and for your feedback! I'll go fix those
```

links now :)
